// Generated by CoffeeScript 1.8.0
(function() {
  if (!which('nginx')) {
    $('apt-get update');
    $('apt-get install -y nginx');
    $('apt-get clean');
    rm('-rf', ['/var/lib/apt/lists/*', '/tmp/*', '/var/tmp/*']);
    $('service nginx start');
    echo(GET('127.0.0.1'));
  }

}).call(this);
